name: Linux OS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
    - uses: actions/checkout@v2
    - name: setup
      run: project_main.c
    - name: make
      run: make -C Multifile
