name: Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup
      run:  .\a.exe
    - name: make
      run: project_main.c
    - name: check
      run: make check
    - name: make distcheck
      run: make distcheck
